### PR TITLE
Remove any existing jobs on subsequent runs

### PR DESCRIPTION
**Pull request by jsuar**
- Script would error when rerunning the script to add or change domains. It now removes
any existing jobs.
- Updated the README to include the cmdlets to remove jobs.

### CODE REVIEW

**Comment by jsuar** [comment]
Yes, I'll provide output of before and after the changes soon. Thanks!

**Comment by jsuar** [comment]
**Original Code**
The original code produces the following output on subsequent runs.
```
PS C:\Users\...\Enable-DuckDns> .\Enable-DuckDNS-orig.ps1 -MyDomains "wibble,pibble" -Token YourDuckDNSToken -Interval 5
Register-ScheduledJob : The scheduled job definition StartDuckDnsJob already exists in the job definition store.
At C:\Users\...\Enable-DuckDnss\Enable-DuckDns-orig.ps1:138 char:5
+     Register-ScheduledJob -Name "StartDuckDnsJob" -ScriptBlock $Setup ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...edJobDefinition:ScheduledJobDefinition) [Register-ScheduledJob], Sched 
   uledJobException
    + FullyQualifiedErrorId : CantRegisterScheduledJobDefinition,Microsoft.PowerShell.ScheduledJob.RegisterScheduledJobCommand
 
Register-ScheduledJob : The scheduled job definition RunDuckDnsUpdate already exists in the job definition store.
At C:\Users\...\Enable-DuckDns\Enable-DuckDns-orig.ps1:99 char:5
+     Register-ScheduledJob -Name "RunDuckDnsUpdate" -ScriptBlock $Upda ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...edJobDefinition:ScheduledJobDefinition) [Register-ScheduledJob], Sched 
   uledJobException
    + FullyQualifiedErrorId : CantRegisterScheduledJobDefinition,Microsoft.PowerShell.ScheduledJob.RegisterScheduledJobCommand
 
All done - your DuckDNS will now update automatically, and will continue to do so across system restarts.
Have a nice day!
PS C:\Users\...\Enable-DuckDns> .\Enable-DuckDNS-orig.ps1 -MyDomains "wibble,pibble" -Token YourDuckDNSToken -Interval 5
Register-ScheduledJob : The scheduled job definition StartDuckDnsJob already exists in the job definition store.
At C:\Users\...\Enable-DuckDns\Enable-DuckDns-orig.ps1:138 char:5
+     Register-ScheduledJob -Name "StartDuckDnsJob" -ScriptBlock $Setup ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...edJobDefinition:ScheduledJobDefinition) [Register-ScheduledJob], Sched 
   uledJobException
    + FullyQualifiedErrorId : CantRegisterScheduledJobDefinition,Microsoft.PowerShell.ScheduledJob.RegisterScheduledJobCommand
 
Register-ScheduledJob : The scheduled job definition RunDuckDnsUpdate already exists in the job definition store.
At C:\Users\...\Enable-DuckDns\Enable-DuckDns-orig.ps1:99 char:5
+     Register-ScheduledJob -Name "RunDuckDnsUpdate" -ScriptBlock $Upda ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...edJobDefinition:ScheduledJobDefinition) [Register-ScheduledJob], Sched 
   uledJobException
    + FullyQualifiedErrorId : CantRegisterScheduledJobDefinition,Microsoft.PowerShell.ScheduledJob.RegisterScheduledJobCommand
 
All done - your DuckDNS will now update automatically, and will continue to do so across system restarts.
Have a nice day!
```

**Updated Code**
Running the updated code produces the following:
```
PS C:\Users\...\Enable-DuckDns> .\Enable-DuckDNS.ps1 -MyDomains "wibble,pibble" -Token YourDuckDNSToken -Interval 5

Id         Name            JobTriggers     Command                                  Enabled   
--         ----            -----------     -------                                  -------   
13         StartDuckDnsJob 1               ...                                      True      
14         RunDuckDnsUp... 1               ...                                      True      
All done - your DuckDNS will now update automatically, and will continue to do so across system restarts.
Have a nice day!
```
A subsequent run removes 13 and 14. The new jobs are now 15 and 16. 

```
PS C:\Users\...\Enable-DuckDns> .\Enable-DuckDNS.ps1 -MyDomains "wibble,pibble" -Token YourDuckDNSToken -Interval 5

Id         Name            JobTriggers     Command                                  Enabled   
--         ----            -----------     -------                                  -------   
15         StartDuckDnsJob 1               ...                                      True      
16         RunDuckDnsUp... 1               ...                                      True      
All done - your DuckDNS will now update automatically, and will continue to do so across system restarts.
Have a nice day!
```

No errors are thrown related to the jobs. This allow for updating the jobs and/or recreating the jobs.

**Comment by godeater** [comment]
Thanks - merged!

**Comment by jsuar** [comment]
Awesome. Thanks for working with me. This was my first public PR :)

**Pull request merged**
